import os
from dotenv import load_dotenv

load_dotenv()

# ── HuggingFace ───────────────────────────────────────────────────────────────

HF_TOKEN: str | None = os.getenv("HF_TOKEN")
HF_USERNAME: str = os.getenv("HF_USERNAME", "")
HF_DATASET_NAME: str = os.getenv("DATASET_NAME", "deep-tech-radar")

# ── Semantic Scholar ──────────────────────────────────────────────────────────

SS_API_KEY: str | None = os.getenv("SS_API_KEY")
SS_MAX_PAPERS: int = 50
CURRENT_YEAR: int = 2025
RECENT_YEARS: int = 3
PAPERS_CACHE_YEARS: int = 5

# ── OpenAI ────────────────────────────────────────────────────────────────────

OPENAI_API_KEY: str | None = os.getenv("OPENAI_API_KEY")
OPENAI_MODEL: str = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
OPENAI_TIMEOUT: int = 120

# ── UI ────────────────────────────────────────────────────────────────────────

APP_TITLE: str = "SINTEF Deep Tech & Skill Radar"
APP_SUBTITLE: str = (
    "Map your research interests, skill radar, expertise, and contribution goals "
    "across deep tech areas — visualised as a group skill radar and find areas "
    "to contribute and create synergy in deep tech for collaborating and deep building."
)

# ── Team ──────────────────────────────────────────────────────────────────────

TEAM_MEMBERS: list[str] = [
    "Sagar Sen",
    "Merve Astekin",
    "Rustem Dautov",
    "Gencer Erdogan",
    "Arda Goknil",
    "Erik Johannes Husom",
    "Phu Nguyen",
    "Karthik Shivashankar",
    "Hui Song",
    "Shukun Tokas",
    "Simeon Tverdal",
    "Adela Nedisan Videsjorden",
    "Sondre Sigstad Wikberg",
]

SCHOLAR_URL_MAP: dict[str, str] = {
    "Karthik Shivashankar":      "https://scholar.google.com/citations?user=OrRAiLoAAAAJ&hl=en",
    "Sagar Sen":                 "https://scholar.google.com/citations?user=aBqoj50AAAAJ&hl=en",
    "Arda Goknil":               "https://scholar.google.com/citations?user=AsUXppAAAAAJ&hl=en",
    "Hui Song":                  "https://scholar.google.com/citations?user=lT6h24IAAAAJ&hl=en",
    "Phu Nguyen":                "https://scholar.google.com/citations?user=Nm4OBGYAAAAJ&hl=en",
    "Rustem Dautov":             "https://scholar.google.com/citations?user=2aWHQCAAAAAJ&hl=en",
    "Gencer Erdogan":            "https://scholar.google.com/citations?user=FOLGI1MAAAAJ&hl=en",
    "Erik Johannes Husom":       "https://scholar.google.com/citations?user=n8l-leAAAAAJ&hl=no",
    "Shukun Tokas":              "https://scholar.google.com/citations?user=zD4LcjsAAAAJ&hl=en",
    "Simeon Tverdal":            "https://scholar.google.com/citations?view_op=list_works&hl=en&user=o39iDR0AAAAJ",
    "Merve Astekin":             "https://scholar.google.com/citations?user=y3n7pxkAAAAJ&hl=en",
    "Adela Nedisan Videsjorden": "https://scholar.google.com/citations?user=sdZqJXMAAAAJ&hl=en",
}

# ── Tech Areas ────────────────────────────────────────────────────────────────

EXTENDED_TECH_AREAS: list[str] = [
    "AI/ML & Trustworthy AI",
    "IoT & Edge Computing",
    "Cybersecurity",
    "Privacy Engineering",
    "Green/Sustainable Computing",
    "Digital Twins",
    "Software Engineering",
    "Cloud & Distributed Systems",
    "Self-Adaptive Systems",
    "Software Quality",
    "Quantum Computing",
    "Blockchain & Distributed Ledger",
    "Robotics & Autonomous Systems",
    "5G & Advanced Networks",
    "Augmented/Virtual Reality",
    "Bioinformatics & Computational Biology",
    "High-Performance Computing",
    "Formal Methods & Verification",
    "Human-Computer Interaction",
    "Natural Language Processing",
    "Computer Vision",
    "Federated Learning",
    "Explainable AI (XAI)",
    "MLOps & AI Engineering",
    "Smart Grid & Energy Systems",
    "Data Governance & Ethics",
    "Hardware Security",
    "Post-Quantum Cryptography",
    "Model-Driven Engineering",
    "DevSecOps & Continuous Delivery",
]

COLLAB_GOALS: list[str] = [
    "Research",
    "Paper Writing",
    "Prototyping",
    "Grant / Funding Proposal",
    "Teaching / Mentoring",
    "Open Source Project",
]

SS_GENERIC_TAGS: frozenset[str] = frozenset({
    "Computer Science", "Mathematics", "Physics", "Engineering",
    "Biology", "Medicine", "Chemistry", "Economics", "Psychology",
    "Sociology", "Philosophy", "History", "Art", "Literature",
    "Environmental Science", "Business", "Political Science",
})

SCHOLAR_TAG_TO_AREA: dict[str, str] = {
    "machine learning":              "AI/ML & Trustworthy AI",
    "deep learning":                 "AI/ML & Trustworthy AI",
    "neural network":                "AI/ML & Trustworthy AI",
    "artificial intelligence":       "AI/ML & Trustworthy AI",
    "large language model":          "AI/ML & Trustworthy AI",
    "natural language processing":   "Natural Language Processing",
    "nlp":                           "Natural Language Processing",
    "computer vision":               "Computer Vision",
    "reinforcement learning":        "AI/ML & Trustworthy AI",
    "federated learning":            "Federated Learning",
    "explainability":                "Explainable AI (XAI)",
    "explainable ai":                "Explainable AI (XAI)",
    "xai":                           "Explainable AI (XAI)",
    "fairness":                      "AI/ML & Trustworthy AI",
    "trustworthy ai":                "AI/ML & Trustworthy AI",
    "responsible ai":                "AI/ML & Trustworthy AI",
    "ai ethics":                     "Data Governance & Ethics",
    "transfer learning":             "AI/ML & Trustworthy AI",
    "generative model":              "AI/ML & Trustworthy AI",
    "llm":                           "AI/ML & Trustworthy AI",
    "transformer":                   "AI/ML & Trustworthy AI",
    "anomaly detection":             "AI/ML & Trustworthy AI",
    "predictive model":              "AI/ML & Trustworthy AI",
    "data science":                  "AI/ML & Trustworthy AI",
    "pattern recognition":           "AI/ML & Trustworthy AI",
    "classification":                "AI/ML & Trustworthy AI",
    "regression":                    "AI/ML & Trustworthy AI",
    "internet of things":            "IoT & Edge Computing",
    "iot":                           "IoT & Edge Computing",
    "edge computing":                "IoT & Edge Computing",
    "fog computing":                 "IoT & Edge Computing",
    "embedded system":               "IoT & Edge Computing",
    "sensor network":                "IoT & Edge Computing",
    "wireless sensor":               "IoT & Edge Computing",
    "mqtt":                          "IoT & Edge Computing",
    "smart device":                  "IoT & Edge Computing",
    "industrial iot":                "IoT & Edge Computing",
    "iiot":                          "IoT & Edge Computing",
    "edge intelligence":             "IoT & Edge Computing",
    "cyber-physical":                "IoT & Edge Computing",
    "real-time system":              "IoT & Edge Computing",
    "smart manufacturing":           "IoT & Edge Computing",
    "pervasive computing":           "IoT & Edge Computing",
    "ubiquitous computing":          "IoT & Edge Computing",
    "wearable":                      "IoT & Edge Computing",
    "cybersecurity":                 "Cybersecurity",
    "cyber security":                "Cybersecurity",
    "information security":          "Cybersecurity",
    "network security":              "Cybersecurity",
    "intrusion detection":           "Cybersecurity",
    "vulnerability":                 "Cybersecurity",
    "malware":                       "Cybersecurity",
    "threat detection":              "Cybersecurity",
    "access control":                "Cybersecurity",
    "authentication":                "Cybersecurity",
    "encryption":                    "Cybersecurity",
    "cryptography":                  "Cybersecurity",
    "security testing":              "Cybersecurity",
    "penetration testing":           "Cybersecurity",
    "zero trust":                    "Cybersecurity",
    "attack detection":              "Cybersecurity",
    "supply chain security":         "Cybersecurity",
    "secure coding":                 "Cybersecurity",
    "privacy":                       "Privacy Engineering",
    "data privacy":                  "Privacy Engineering",
    "privacy by design":             "Privacy Engineering",
    "differential privacy":          "Privacy Engineering",
    "anonymization":                 "Privacy Engineering",
    "anonymisation":                 "Privacy Engineering",
    "gdpr":                          "Privacy Engineering",
    "data protection":               "Privacy Engineering",
    "privacy-preserving":            "Privacy Engineering",
    "consent management":            "Privacy Engineering",
    "k-anonymity":                   "Privacy Engineering",
    "secure multiparty computation": "Privacy Engineering",
    "personal data":                 "Privacy Engineering",
    "green computing":               "Green/Sustainable Computing",
    "sustainable computing":         "Green/Sustainable Computing",
    "energy efficiency":             "Green/Sustainable Computing",
    "energy consumption":            "Green/Sustainable Computing",
    "carbon footprint":              "Green/Sustainable Computing",
    "green software":                "Green/Sustainable Computing",
    "sustainability":                "Green/Sustainable Computing",
    "low-power":                     "Green/Sustainable Computing",
    "environmental impact":          "Green/Sustainable Computing",
    "net zero":                      "Green/Sustainable Computing",
    "carbon-aware":                  "Green/Sustainable Computing",
    "renewable energy":              "Green/Sustainable Computing",
    "digital twin":                  "Digital Twins",
    "model-driven engineering":      "Model-Driven Engineering",
    "simulation":                    "Digital Twins",
    "virtual model":                 "Digital Twins",
    "predictive maintenance":        "Digital Twins",
    "mde":                           "Model-Driven Engineering",
    "model synchronization":         "Model-Driven Engineering",
    "runtime model":                 "Digital Twins",
    "system modeling":               "Digital Twins",
    "ocl":                           "Model-Driven Engineering",
    "software engineering":          "Software Engineering",
    "software development":          "Software Engineering",
    "agile":                         "Software Engineering",
    "devops":                        "DevSecOps & Continuous Delivery",
    "continuous integration":        "DevSecOps & Continuous Delivery",
    "software testing":              "Software Engineering",
    "test automation":               "Software Engineering",
    "software architecture":         "Software Engineering",
    "software design":               "Software Engineering",
    "requirements engineering":      "Software Engineering",
    "model-based testing":           "Software Engineering",
    "refactoring":                   "Software Engineering",
    "program analysis":              "Software Engineering",
    "static analysis":               "Software Engineering",
    "software maintenance":          "Software Engineering",
    "code review":                   "Software Engineering",
    "api design":                    "Software Engineering",
    "cloud computing":               "Cloud & Distributed Systems",
    "distributed system":            "Cloud & Distributed Systems",
    "serverless":                    "Cloud & Distributed Systems",
    "kubernetes":                    "Cloud & Distributed Systems",
    "container":                     "Cloud & Distributed Systems",
    "service mesh":                  "Cloud & Distributed Systems",
    "stream processing":             "Cloud & Distributed Systems",
    "fault tolerance":               "Cloud & Distributed Systems",
    "scalability":                   "Cloud & Distributed Systems",
    "distributed computing":         "Cloud & Distributed Systems",
    "microservice":                  "Cloud & Distributed Systems",
    "cloud-native":                  "Cloud & Distributed Systems",
    "consensus algorithm":           "Cloud & Distributed Systems",
    "service-oriented":              "Cloud & Distributed Systems",
    "self-adaptive":                 "Self-Adaptive Systems",
    "self-healing":                  "Self-Adaptive Systems",
    "self-organizing":               "Self-Adaptive Systems",
    "autonomic computing":           "Self-Adaptive Systems",
    "feedback control":              "Self-Adaptive Systems",
    "runtime adaptation":            "Self-Adaptive Systems",
    "context-aware":                 "Self-Adaptive Systems",
    "adaptive system":               "Self-Adaptive Systems",
    "mape-k":                        "Self-Adaptive Systems",
    "dynamic reconfiguration":       "Self-Adaptive Systems",
    "technical debt":                "Software Quality",
    "code smell":                    "Software Quality",
    "software quality":              "Software Quality",
    "maintainability":               "Software Quality",
    "software metrics":              "Software Quality",
    "software evolution":            "Software Quality",
    "legacy system":                 "Software Quality",
    "architecture erosion":          "Software Quality",
    "defect prediction":             "Software Quality",
    "code coverage":                 "Software Quality",
    "software reliability":          "Software Quality",
    "quantum":                       "Quantum Computing",
    "blockchain":                    "Blockchain & Distributed Ledger",
    "distributed ledger":            "Blockchain & Distributed Ledger",
    "smart contract":                "Blockchain & Distributed Ledger",
    "robot":                         "Robotics & Autonomous Systems",
    "autonomous system":             "Robotics & Autonomous Systems",
    "5g":                            "5G & Advanced Networks",
    "augmented reality":             "Augmented/Virtual Reality",
    "virtual reality":               "Augmented/Virtual Reality",
    "bioinformatics":                "Bioinformatics & Computational Biology",
    "hpc":                           "High-Performance Computing",
    "high-performance computing":    "High-Performance Computing",
    "formal method":                 "Formal Methods & Verification",
    "model checking":                "Formal Methods & Verification",
    "theorem proving":               "Formal Methods & Verification",
    "human-computer interaction":    "Human-Computer Interaction",
    "hci":                           "Human-Computer Interaction",
    "mlops":                         "MLOps & AI Engineering",
    "smart grid":                    "Smart Grid & Energy Systems",
    "data governance":               "Data Governance & Ethics",
    "hardware security":             "Hardware Security",
    "post-quantum":                  "Post-Quantum Cryptography",
    "devsecops":                     "DevSecOps & Continuous Delivery",
}
